---
- name: Validate that distribution info is available are available
  setup:
  when: ansible_distribution_major_version is not defined or ansible_distribution is not defined or ansible_bios_version is not defined

- name: Configure EPEL with no proxy
  include_tasks: with_no_proxy.yml
  when: (https_proxy is not defined or https_proxy | trim == '') and (http_proxy is not defined or http_proxy | trim == '') and (no_proxy is not defined or no_proxy | trim == '')

- name: Configure EPEL with proxy
  include_tasks: with_proxy.yml
  when: (https_proxy is defined or https_proxy | trim != '') and (http_proxy is defined or http_proxy | trim != '') and (no_proxy is defined or no_proxy | trim != '')
