---
- name: Validate that distribution info is available are available
  setup:
  when: ansible_distribution_major_version is not defined or ansible_distribution is not defined or ansible_bios_version is not defined

- block:
  - name: Update redhat yum client
    become: yes
    shell: "yum update rh-amazon-rhui-client.noarch"

  - name: Configure AWS AMI OS package manager repositories for Apigee
    become: yes
    shell: "/usr/bin/yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional"
  when: ansible_bios_version | lower is search('amazon') and ansible_distribution | lower != 'redhat' and ansible_distribution_major_version is version_compare('6', '>')

- name: Register with Redhat Subscription management
  become: yes
  shell: "subscription-manager register --username={{ rhel_user_name }} --password={{ rhel_password }} --auto-attach"
  when: ansible_distribution | lower == 'redhat' and ansible_distribution_major_version is version_compare('7', '>')

- name: Configure AWS AMI OS package manager repositories for Apigee
  become: yes
  shell: "/usr/bin/yum-config-manager --enable ol7_optional_latest"
  when: ansible_distribution | lower == 'oraclelinux' and ansible_distribution_major_version is version_compare('7', '>')

- name: Remove existing epel repository references
  become: yes
  yum:
    name: epel-release
    state: absent
  when: opdk_version is version_compare('4.17.05', '<=')
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"

- name: Yum clean
  become: yes
  shell: "yum clean all"
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"

- name: Remove yum cache
  become: yes
  file:
    path: /var/cache/yum
    state: absent

- block:
  - name: Update with EPEL downgrade allowed if 4.17.09 or greater
    become: yes
    yum:
      name: epel-release
      state: present
      allow_downgrade: yes
    when: opdk_version is version_compare('4.17.05', '>')
    environment:
      http_proxy: "{{ http_proxy }}"
      https_proxy: "{{ https_proxy }}"
      no_proxy: "{{ no_proxy }}"

  rescue:
    - block:
      - name: Update EPEL with direct rpm if 4.17.05 or less
        become: yes
        yum:
          name: "{{ epel_repo }}"
          state: present
        environment:
          http_proxy: "{{ http_proxy }}"
          https_proxy: "{{ https_proxy }}"
          no_proxy: "{{ no_proxy }}"
    rescue:
      - name: Update EPEL with direct rpm if 4.17.05 or less
        become: yes
        yum:
          name: "{{ epel_repo }}"
          state: present
          disable_gpg_check: yes
        environment:
          http_proxy: "{{ http_proxy }}"
          https_proxy: "{{ https_proxy }}"
          no_proxy: "{{ no_proxy }}"


- name: Check for existence of epel.repo
  stat:
    path: /etc/yum.repos.d/epel.repo
  register: epel

- name: expose baseurl in epel.repo definition
  become: true
  replace:
    backup: yes
    regexp: '^(#baseurl=)(.*)'
    replace: 'baseurl=\2'
    dest: /etc/yum.repos.d/epel.repo
  when: epel.stat.exists
