---
# tasks file for apigee-opdk-setup-epel
- name: Update EPEL with proxy
  yum:
    name: epel-release
    state: absent
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"

- name: Update EPEL with proxy
  yum:
    name: epel-release
    state: present
    allow_downgrade: yes
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"

- name: Update EPEL with proxy
  yum:
    name: "{{ epel_repo }}"
    state: present
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
