---
# tasks file for apigee-opdk-setup-epel
- name: Configure AWS AMI OS package manager repositories for Apigee
  shell: "/usr/bin/yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional"
  when: ansible_bios_version | lower | search('amazon') and ansible_distribution | lower != 'redhat' and ansible_distribution_major_version | version_compare('6', '>')

# TODO: Look up the ansible_distribution name for RHEL systems
- name: If using RHEL then register RHEL on RHN
  shell: "subscription-manager register --username={{ rhel_user_name }} --password={{ rhel_password }} --auto-attach"
  when: ansible_bios_version | lower | search('amazon') and ansible_distribution | lower == 'redhat' and ansible_distribution_major_version | version_compare('7', '>')

- name: Update EPEL with no proxy
  yum:
    name: epel-release
    state: absent
  when: opdk_version | version_compare('4.16.09', '==')

#- name: Update EPEL with no proxy
#  yum:
#    name: epel-release
#    allow_downgrade: yes
#    state: present

- name: Update EPEL with no proxy
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  when: opdk_version | version_compare('4.17.05', '>')

- block:
  - name: Remove epel
    yum:
      name: epel-release
      state: absent

  - name: Update with EPEL 6 with no proxy
    yum:
      name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm"
      state: present
  when: opdk_version | version_compare('4.17.05', '<=')
