---
# tasks file for apigee-opdk-setup-epel
- name: Update EPEL with no proxy
  become: yes
  yum:
    name: epel-release
    state: absent
  when: opdk_version | version_compare('4.16.09', '==')

#- name: Update EPEL with no proxy
#  yum:
#    name: epel-release
#    allow_downgrade: yes
#    state: present

- name: Update EPEL with no proxy
  become: yes
  yum:
    name: "{{ epel_repo }}"
    state: present
  when: opdk_version | version_compare('4.17.05', '>')

- block:
  - name: Remove epel
    become: yes
    yum:
      name: epel-release
      state: absent

  - name: Yum clean
    become: yes
    shell: "yum clean all"

  - name: Remove yum cache
    become: yes
    file:
      path: /var/cache/yum
      state: absent

  - name: Update with EPEL 6 with no proxy
    become: yes
    yum:
      name: "{{ epel_7_repo }}"
      state: present
  when: opdk_version | version_compare('4.17.05', '<=')
